package.json

Jest tests now run concurrently instead of one package at a time. Addresses issue #10.
@cerner/terra

Execute Jest tests concurrently.

---

packages/terra-clinical-detail-view/package.json
packages/terra-clinical-item-view/package.json

Specified the webpack_config_path for each nightwatch test script. Addresses issue #9. 
All new packages will need to include `WEBPACK_CONFIG_PATH=../../../../terra-clinical-site/webpack.config` in the test scripts for nightwatch tests to run on a package level.

Included webpack_config_path in test scripts.

---

packages/terra-clinical-label-value-view/tests/nightwatch/LabelValueViewTests.jsx

The link `LabelValueView with a Node Input` was incorrect and resulted in no example being loaded. Fixed to display the example on the site.
@cerner/terra

Fix Label Value View Test Route

---

Procfile
app.json
package.json
packages/terra-clinical-site/package.json
packages/terra-clinical-site/webpack.config.js
scripts/express/README.md
scripts/express/app.js

A heroku application and pipeline was created for terra-clinical. Addresses issue #57. 
The changes in this pull request are:
1. Add `app.json` for heroku app.
2. Add `scripts/express` for express server.
3. Update `package.json` to add express and heroku scripts.
4. Update `terra-clincial-site/package.json` to add heroku script.
4. Add config to `webpack.config.js` to disable host check from webpack-dev-server.
5. Add `Procfile` to specify heroku server command
These changes reflect changes made [here](https://github.com/cerner/terra-core/pull/318) and [here](https://github.com/cerner/terra-core/pull/326).
@cerner/terra

Heroku configuration & scripts. Express scripts.

---

nightwatch.conf.js
packages/terra-clinical-action-header/tests/nightwatch.conf.js
packages/terra-clinical-detail-view/tests/nightwatch.conf.js
packages/terra-clinical-error-view/tests/nightwatch.conf.js
packages/terra-clinical-header/tests/nightwatch.conf.js
packages/terra-clinical-item-display/tests/nightwatch.conf.js
packages/terra-clinical-item-view/tests/nightwatch.conf.js
packages/terra-clinical-label-value-view/tests/nightwatch.conf.js
packages/terra-clinical-no-data-view/tests/nightwatch.conf.js
packages/terra-clinical-site/webpack.config.js
packages/terra-clinical-site/webpack.prod.config.js
tests/nightwatch.conf.js

This PR addresses three issues:
1. Fixes types in the devServ configuration which is causing an error when running the script `npm run start`
2. Removes relative paths for terra-toolkit in the  `nightwatch.conf.js` files
3. Removes the configuration that defined production in the `terra-clinical-site/webpack.prod.config.js` file. The `-p` flag in the `compile:prod` and `compile:prod-stats` handle's this.
@cerner/terra

Fix Configurations

---

.eslintignore
packages/terra-clinical-application/tests/jest/__snapshots__/Application.test.jsx.snap
packages/terra-clinical-modal-manager/tests/nightwatch/modal-manager-spec.js
packages/terra-clinical-site/aggregated-translations/de.js
packages/terra-clinical-site/aggregated-translations/en-GB.js
packages/terra-clinical-site/aggregated-translations/en-US.js
packages/terra-clinical-site/aggregated-translations/en.js
packages/terra-clinical-site/aggregated-translations/es.js
packages/terra-clinical-site/aggregated-translations/fi-FI.js
packages/terra-clinical-site/aggregated-translations/fr.js
packages/terra-clinical-site/aggregated-translations/pt.js
packages/terra-clinical-site/package.json
packages/terra-clinical-site/src/App.jsx
packages/terra-clinical-site/webpack.config.js

With `terra-base` v0.5.0 released, the `terra-i18n-plugin` needed incorporated into terra-clinical-site webpack configuration. Without the integration, errors were thrown and the script `npm run start` failed to compile. 
@cerner/terra

Integrate terra-i18n-plugin into webpack config.

---

packages/terra-clinical-action-header/translations/en.json

Adding `en` translations for terra-clincial action header.
Supported locales
https://github.com/cerner/terra-core/blob/cb6e4259e33af5ddad2ca1a6cdca07fb819eaebf/packages/terra-i18n/src/i18nSupportedLocales.js
@cerner/terra

Adding en translations for terra-clinical-action-header

---

packages/terra-clinical-item-display/src/ItemComment.scss
packages/terra-clinical-item-display/src/ItemDisplay.scss
packages/terra-clinical-item-display/src/_mixins.scss
packages/terra-clinical-item-view/src/ItemView.scss

Looking at the Item Display site page, the bottom of the text is cut off.  When the item-display was a subcomponent of the item-view, the item-view handled the styling that applied a default font-size and line-height. This PR moves this default styling into the item-display package. 
@cerner/terra

Update Item Display Styling

---

.gitignore
package.json
packages/terra-clinical-action-header/package.json
packages/terra-clinical-application/package.json
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-error-view/package.json
packages/terra-clinical-header/package.json
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/package.json
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-modal-manager/package.json
packages/terra-clinical-no-data-view/package.json
packages/terra-clinical-slide-group/package.json

Generating a props-table for each component when publishing. This matches the work done in terra-core here: https://github.com/cerner/terra-core/pull/473 
In terra-core, terra-props-table is installed in each package. In terra-clinical, we only need to install it in the root package.json. 
@cerner/terra

props-table-cli

---

packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/src/ItemView.jsx
packages/terra-clinical-item-view/src/ItemView.scss
packages/terra-clinical-item-view/tests/jest/__snapshots__/ItemView.test.jsx.snap
packages/terra-clinical-item-view/tests/nightwatch/AccessoryItemView.jsx
packages/terra-clinical-item-view/tests/nightwatch/CommentItemView.jsx
packages/terra-clinical-item-view/tests/nightwatch/ItemViewTestRoutes.jsx
packages/terra-clinical-item-view/tests/nightwatch/ItemViewTests.jsx
packages/terra-clinical-item-view/tests/nightwatch/OverflowDisplaysItemView.jsx
packages/terra-clinical-item-view/tests/nightwatch/item-view-spec.js

This PR addresses a few issues with Item View.
1. Fixes Icon Scaling. Closes #115.
2. When adding an example in the nightwatch for scaling, added icons to the accessory examples to provide more context. Closes #149.
3. Fixed Truncation styling. Closes #148.
4. Updated class names to use a '-' instead of a '--'.
@cerner/terra

Fix Item View UX Issues

---

packages/terra-clinical-action-header/CHANGELOG.md
packages/terra-clinical-action-header/src/ActionHeader.jsx
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/src/DetailList.jsx
packages/terra-clinical-detail-view/tests/jest/DetailList.test.jsx
packages/terra-clinical-detail-view/tests/jest/__snapshots__/DetailList.test.jsx.snap
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/src/ItemCollection.jsx
packages/terra-clinical-item-collection/src/_CreateTableView.jsx
packages/terra-clinical-item-collection/src/_TableHeaderCell.jsx
packages/terra-clinical-item-collection/tests/jest/__snapshots__/ItemCollection.test.jsx.snap
packages/terra-clinical-item-collection/tests/jest/__snapshots__/TableHeaderCell.test.jsx.snap
packages/terra-clinical-item-collection/tests/nightwatch/item-collection/clinical-item-collection-spec.js
packages/terra-clinical-item-collection/tests/nightwatch/table-header-cell/table-header-cell-spec.js
packages/terra-clinical-site/CHANGELOG.md
packages/terra-clinical-site/src/App.jsx

In this closed PR https://github.com/cerner/terra-core/pull/694 it was discussed to change `data-class` attributes to be name spaced to the rendering component. This PR updates the ActionHeader, DetailList in DetailView, Item Collection and Site components to use name-spaced data attributes.
The use of un-merged `data-class` attributes has caused Travis to recently fail for item-collection nightwatch tests. Item-collection uses terra-table and attempts to apply its own data-classes on different table components, however these are being overridden by table. With these name-spaced data attributes, this will no longer be an issue.
Before the CSS Module conversion, some elements had terra class names to represent the structure of the component but did not apply any styling. In the conversion, …

Update data class attrs

---

packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/src/Header.jsx
packages/terra-clinical-header/tests/jest/__snapshots__/Header.test.jsx.snap
packages/terra-clinical-header/tests/nightwatch/HeaderTestRoutes.jsx
packages/terra-clinical-header/tests/nightwatch/HeaderTests.jsx
packages/terra-clinical-header/tests/nightwatch/NoTitleRightContentHeader.jsx
packages/terra-clinical-header/tests/nightwatch/header-spec.js

Correct implementation for end aligned content when both the start aligned items and title is missing.
Fixes #183 
Deployment: https://terra-clinical-deployed-pr-182.herokuapp.com/static/#/site/header

Fix end aligned content with no text or left content.

---

packages/terra-clinical-action-header/CHANGELOG.md
packages/terra-clinical-action-header/package.json
packages/terra-clinical-application-site/CHANGELOG.md
packages/terra-clinical-application-site/package.json
packages/terra-clinical-application/CHANGELOG.md
packages/terra-clinical-application/package.json
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-detail-view/src/DetailView.scss
packages/terra-clinical-error-view/CHANGELOG.md
packages/terra-clinical-error-view/package.json
packages/terra-clinical-error-view/src/ErrorView.scss
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json
packages/terra-clinical-header/src/Header.scss
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/package.json
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-no-data-view/CHANGELOG.md
packages/terra-clinical-no-data-view/package.json
packages/terra-clinical-no-data-view/src/NoDataView.scss

Updating all components that had a dependency on base to use terra-base@2.0.0.
Added margin resets to elements used in clinical components which used to have margin reset in terra-base@1.0.0
@cerner/terra

Update components to use terra-base 2.0.0

---

jestconfig.json
package.json
packages/terra-clinical-action-header/package.json
packages/terra-clinical-action-header/tests/jest/__snapshots__/ActionHeader.test.jsx.snap
packages/terra-clinical-application/package.json
packages/terra-clinical-application/tests/jest/__snapshots__/Application.test.jsx.snap
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-detail-view/tests/jest/__snapshots__/DetailList.test.jsx.snap
packages/terra-clinical-detail-view/tests/jest/__snapshots__/DetailListItem.test.jsx.snap
packages/terra-clinical-detail-view/tests/jest/__snapshots__/DetailView.test.jsx.snap
packages/terra-clinical-error-view/package.json
packages/terra-clinical-error-view/tests/jest/__snapshots__/ErrorView.test.jsx.snap
packages/terra-clinical-header/package.json
packages/terra-clinical-header/tests/jest/__snapshots__/Header.test.jsx.snap
packages/terra-clinical-item-collection/package.json
packages/terra-clinical-item-collection/tests/jest/__snapshots__/ItemCollection.test.jsx.snap
packages/terra-clinical-item-collection/tests/jest/__snapshots__/TableHeaderCell.test.jsx.snap
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-display/tests/jest/__snapshots__/ItemComment.test.jsx.snap
packages/terra-clinical-item-display/tests/jest/__snapshots__/ItemDisplay.test.jsx.snap
packages/terra-clinical-item-view/package.json
packages/terra-clinical-item-view/tests/jest/__snapshots__/ItemView.test.jsx.snap
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-label-value-view/tests/jest/__snapshots__/LabelValueView.test.jsx.snap
packages/terra-clinical-no-data-view/package.json
packages/terra-clinical-no-data-view/tests/jest/__snapshots__/NoDataView.test.jsx.snap

Sync with terra-clinal PR #798 which references issue #323 to update Jest dependency.
With Jest v21, compared to Jest v18, snapshots have some changes in how they are rendering.
Closing angle brackets are rendered on their own line.
```diff
<div>
-  className="test">
+   className="test"
+ >
```
```diff
- }>
+  }
+ >
```
The word `test` is no longer included in export in snapshot
```diff
- exports[`test should render ...`] = `
+ exports[`should render ...`] = `
```
Snapshots include version number in snapshot
```diff
+ // Jest Snapshot v1, https://goo.gl/fbAQLP
```
DOM elements / React Components which were empty now render differently
```diff
- <div />
+ <div>
+ 
+ </div>
```
This is the majority of the diffs in this PR.

Update jest to v21.0.2

---

package.json
packages/terra-clinical-site/CHANGELOG.md
packages/terra-clinical-site/package.json

Webpack > 2.7.1 dropped IE 10 & 11 support.
See https://github.com/cerner/terra-core/pull/901
@cerner/terra

Set webpack dev server at 2.7.1 for IE10 compatibility

---

packages/terra-clinical-site/CHANGELOG.md
packages/terra-clinical-site/package.json
packages/terra-clinical-site/src/App.jsx
packages/terra-clinical-site/src/site.scss

Uplifted terra-clinical-site to use the collapsible menu view such that the options collapse at smaller view port sizes. Closes #202.

Update Site Header to use Collapsible Menu View 

---

packages/terra-clinical-site/.gitignore
packages/terra-clinical-site/package.json

Removing the large stats log for a production build command. Also removing the command altogether.

Removing unnecessary stats file from version control

---

CONTRIBUTORS.md
packages/terra-clinical-item-collection/README.md

Closes #214 
Updated broken documentation link to point to https://github.com/cerner/terra-clinical/tree/master/packages/terra-clinical-item-collection/docs

Fix item collection documentation link

---

.travis.yml
README.md
package.json

Upgrades toolkit to 2.2.0. This moves all testing into docker containers and enables webdriver.io testing.

Terra toolkit upgrade

---

packages/terra-clinical-application-site/package.json
packages/terra-clinical-application-site/webpack.config.js
packages/terra-clinical-site/package.json
packages/terra-clinical-site/postcss.config.js
packages/terra-clinical-site/webpack.config.js

* add postcssassets-plugin
This enables us to compile themes using the `:root` selector to static values for testing theming in browsers that lack support for CSS custom properties.
Sync with https://github.com/cerner/terra-core/pull/971
@cerner/terra

Add postcssassets-plugin

---

packages/terra-clinical-site/CHANGELOG.md
packages/terra-clinical-site/src/App.jsx
packages/terra-clinical-site/src/site.scss

Summary
Remove sites flickering header background on initial page load, by placing the background on a parent div.
Thanks for contributing to Terra.
@cerner/terra

Remove flickering initial header background.

---

packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/src/_ListView.jsx
packages/terra-clinical-item-collection/src/_TableView.jsx

This change passes the Item Collection's view to any custom component that is passed into the Item Collection. This allows custom component to know when to render as a list item or a table row.

Item Collection Pass Back View

---

packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/src/Item.jsx
packages/terra-clinical-item-collection/src/_ListView.jsx
packages/terra-clinical-item-collection/src/_TableView.jsx
packages/terra-clinical-item-collection/tests/jest/Item.test.jsx
packages/terra-clinical-item-collection/tests/jest/__snapshots__/Item.test.jsx.snap
packages/terra-clinical-item-collection/tests/jest/__snapshots__/ItemCollection.test.jsx.snap
packages/terra-clinical-item-collection/tests/jest/__snapshots__/_ListView.test.jsx.snap
packages/terra-clinical-item-collection/tests/jest/__snapshots__/_TableView.test.jsx.snap
packages/terra-clinical-item-collection/tests/nightwatch/item-collection/ItemCollectionSelectable.jsx

* Add `showListItemChevron` prop to allow list items to display a chevron
* Expose all Item Collection generated props that are passed to the children when generating a list or table view

[Item Collection] Add Chevron Prop & Expose IC Generated Props

---

.travis.yml
package.json
wdio.conf.js

Two days ago docker-selenium [released a new version](https://github.com/SeleniumHQ/docker-selenium/commit/cfc1eeb5cdcea02395016685d7012688768ed342) of both selenium/node-chrome and selenium/standalone-chrome. In our tests we pull in the latest tag of both.
The previous version is `3.8.1-erbium` and the latest release is `3.8.1-francium`. 
This pulls the previous version to see if this resolves the issues we are seeing with the repeated
` Expected element ' ' to be present - element was not found`

Lock down docker-selenium Version

---

README.md

Emoji do not render in our static deployed site. This PR replaces the status emoji with shields (which are externally hosted) to keep the read me consistent across deployments of the site.
@cerner/terra

Replace status emoji with shields

---

CONTRIBUTORS.md
packages/terra-clinical-action-header/CHANGELOG.md
packages/terra-clinical-action-header/src/ActionHeader.jsx
packages/terra-clinical-action-header/tests/jest/__snapshots__/ActionHeader.test.jsx.snap
packages/terra-clinical-action-header/tests/nightwatch/ActionHeaderTestRoutes.jsx
packages/terra-clinical-action-header/tests/nightwatch/ActionHeaderTests.jsx
packages/terra-clinical-action-header/tests/nightwatch/KeepCloseButtonActionHeader.jsx
packages/terra-clinical-action-header/tests/nightwatch/action-header-spec.js
packages/terra-clinical-site/src/examples/action-header/ActionHeader-BackNextPreviousClose.jsx
packages/terra-clinical-site/src/examples/action-header/ActionHeader-KeepClose.jsx
packages/terra-clinical-site/src/examples/action-header/Index.jsx

This gives option to the consumers to opt out of the default close button behavior on small view ports in terra-clinical-action-header. https://github.com/cerner/terra-clinical/blob/terra-clinical-header%401.7.0/packages/terra-clinical-action-header/src/ActionHeader.jsx#L27
The default behavior is:
"On small viewports a back button will be displayed instead of a close button when a separate onBack callback is not set"
This change adds a new boolean prop `keepCloseButton` (you can suggest a better name) which when set true will disable the default behavior.

Add option to display close button on small viewports

---

.travis.yml

Disabling cache in travis-ci to avoid problems seen when using outdated dependancies
@cerner/terra

Disable cache for travis-ci build

---

README.md
packages/terra-clinical-application/docs/README.md
packages/terra-clinical-detail-view/docs/README.md
packages/terra-clinical-header/docs/README.md
packages/terra-clinical-item-collection/docs/README.md
packages/terra-clinical-item-display/docs/README.md
packages/terra-clinical-item-view/docs/README.md
packages/terra-clinical-label-value-view/docs/README.md
packages/terra-clinical-onset-picker/docs/README.md

They were point to terra-core's wiki pages we removed in favor of Terra-UI containing the information.
I opted to point directly to the Markdown page instead of the deployed site page https://engineering.cerner.com/terra-ui/#/contributing/terra-ui/component-standards. My thought being the markdown hash routing requires some thinking /work to add the additional routes to the dev-site page for markdown anchors and this directs people to the correct sections.

Update Component Feature Links in Readmes

---

.travis.yml

Using `npm run danger; npm run lint; npm run jest` instead of `npm run danger && npm run lint && npm run jest` doesn't fail the build. The `;` will execute the next script regardless of exit code.

Fail on Danger or Lint

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/src/DataGrid.jsx

In scenarios where rows are being removed from the DataGrid, but there are still more rows to load into the DataGrid through paging (:S), the DataGrid would incorrectly determine the content offset values and fail to request more content.
To fix this:
* I stopped caching one of the height values I was using. It was largely unnecessary.
* I moved the paging request logic into the animation frame that is updating the DOM values to ensure the proper height values are used to determine whether the paging request should be made.

Updating DataGrid paging logic to ensure DOM updates are completed before content requests are made

---

CONTRIBUTORS.md
packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/docs/README.md
packages/terra-clinical-data-grid/src/subcomponents/SectionHeader.jsx
packages/terra-clinical-data-grid/tests/jest/subcomponents/__snapshots__/SectionHeader.test.jsx.snap

Adds an attribute on the section header of terra-clinical-data-grid that is unique to the section id.
For one of our use cases, we'd like to scroll the header into view on component mount. This change lets us properly do this.
https://github.com/cerner/terra-clinical/issues/457

Add section id attribute on DataGrid headers

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/src/DataGrid.jsx

A consumer of the DataGrid ran into a workflow that both updated a DataGrid and unmounted the same DataGrid very quickly. This was causing the animation frame logic triggered by the update to execute _after_ the component unmounted and after all the elements have gone out of scope.
To prevent this from happening, we're going to cancel any pending animation frames during the DataGrid's componentWillUnmount lifecycle implementation. I'm canceling the animation frame logic that synchronizes the horizontal scroll positioning for good measure.
I also cleaned up the unnecessary checks around the presence of those animation frame ids before canceling them. Calling cancelAnimationFrame with undefined is supported, and the animation frame ids will persist even after they have executed, so the …

[terra-clinical-data-grid] Updating unmount implementation to cancel any pending animation frames

---

packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/tests/jest/__snapshots__/OnsetPicker.test.jsx.snap

Onset Date Picker jest tests are failing due to recently released select accessibility changes. Regenerated jest snapshots.

Regenerate jest snapshots for onset date picker

---

.travis.yml
README.md
packages/terra-clinical-application/README.md
packages/terra-clinical-data-grid/README.md
packages/terra-clinical-detail-view/README.md
packages/terra-clinical-header/README.md
packages/terra-clinical-item-collection/README.md
packages/terra-clinical-item-display/README.md
packages/terra-clinical-item-view/README.md
packages/terra-clinical-label-value-view/README.md
packages/terra-clinical-onset-picker/README.md

Updates travis build status badges to point to `travis-ci.com` instead of `travis-ci.org`
Closes #508

Update badges to point to travis-ci.com

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/tests/wdio/data-grid-spec.js

We are having an issue with consistency in our tests with one of the internal themes where it sometimes has a hover effect.  This will move the cursor out of the way to ensure that doesn't happen.

Make tests consistent

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/src/utils/keycodes.js

In https://github.com/cerner/terra-clinical/pull/479 we removed custom keycodes in favor of using `keycodes-js`. Looks like this file was missed in cleanup.

Remove un-used keycodes file

---

packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json

Now that all the components with en-CA are released, we now can see that terra-aggregate-translation reports that  the `Terra/terra-clinical/node_modules/terra-i18n/translations/en-CA.json.` translation file is missing. The en-CA.json for terra-i18n was added in version 4.15.0 but terra-onset-picker has a dependency on version 3.X.X. After further digging, it does not appear that terra-onset-picker uses terra-i18n or has a need for it. Therefore, removing terra-i18n as a dependency terra-onset-picker.

Remove terra-i18n as a dependency since it is not being used or needed.

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/src/DataGrid.jsx
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/src/OnsetPicker.jsx
packages/terra-clinical-onset-picker/tests/jest/__snapshots__/OnsetPicker.test.jsx.snap

Mark `intl` prop as private since it is retrieved from the context automatically by injectIntl.

Label `intl` Prop as Private

---

packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/docs/README.md

Remove yarn reference in docs. We don't support yarn first-class.

Remove yarn ref in docs 

---

packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/tests/jest/__snapshots__/Item.test.jsx.snap
packages/terra-clinical-item-collection/tests/jest/__snapshots__/ItemCollection.test.jsx.snap
packages/terra-clinical-item-collection/tests/jest/__snapshots__/_ListView.test.jsx.snap
packages/terra-clinical-item-collection/tests/jest/__snapshots__/_TableView.test.jsx.snap

When item-display was updated to include a default textStyle of `primary`, tests here were also updated. Since that change was released as a MVB it longer gets pulled in causing these updated tests to fail.
Closes #
@cerner/terra

Fixing Jest tests

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-data-grid/src/DataGrid.jsx
packages/terra-clinical-data-grid/src/subcomponents/Cell.jsx
packages/terra-clinical-data-grid/src/subcomponents/SectionHeader.jsx
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/package.json
packages/terra-clinical-item-collection/src/_ItemCollectionUtils.jsx

The open issue #656 identified an older version (v1) of keycode-js still being used in terra-clinical-data-grid. I saw the same older version being used in terra-clinical-item-collection so I updated that to version 2 as well.
Closes #656
Ran Jest tests and WDIO tests locally for terra-clinical-data-grid and terra-clinical-item-collection. None of the snapshots or screenshots needed to be updated.
@cerner/terra

[terra-clinical-data-grid][terra-clinical-item-collection] Updated keycode-js to v2

---

package.json

Downgraded postcss to 8.3.11 as css linter is failing for postcss version 8.4 and above.
Closes #
@cerner/terra

[terra-clinical]Fix scss lint failing due to latest version of postcss 

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-data-grid/src/utils/dataGridUtils.js
packages/terra-clinical-data-grid/tests/jest/utils/dataGridUtils.test.js

- This PR also publishes the fix so I don't need to issue a separate release PR.
- Where all rows in all sections are marked as decorative (`isDecorative`), the following error is thrown in `getFirstAndLastVisibleRowData` because no decorative rows are found to access the id.
Closes: UXPLATFORM-6501
This change has been tested by providing a packed .tgz file to the engineer who reported the issue and verified that the error no longer occurs with this change.
@cerner/terra

[terra-clinical-data-grid] Decorative row error

---

packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-display/src/ItemComment.jsx
packages/terra-clinical-item-display/src/ItemDisplay.jsx
packages/terra-clinical-item-display/src/terra-dev-site/doc/clinical-item-display/clinicalItemDisplay.1.doc.mdx
packages/terra-clinical-item-display/src/terra-dev-site/doc/example/TruncatedText.jsx
packages/terra-clinical-item-display/src/terra-dev-site/doc/example/TruncatedTextSlidePanel.jsx

This change adds accessibility guidance in the `terra-clinical-item-display` documentation so that consumers are informed of requirements for ensuring accessibility when using the `isTruncated` prop.
This PR only includes documentation updates, so no tests are needed.
UXPLATFORM-8574 
---
@cerner/terra

[terra-clinical-item-display] Add accessibility guidance for isTruncated prop

---

CONTRIBUTORS.md
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/src/DetailList.jsx
packages/terra-clinical-detail-view/src/DetailList.module.scss
packages/terra-clinical-detail-view/src/DetailView.jsx
packages/terra-clinical-detail-view/src/DetailView.module.scss
packages/terra-clinical-detail-view/src/HeadingLevelContext.jsx
packages/terra-clinical-detail-view/src/LevelContext.jsx
packages/terra-clinical-detail-view/src/terra-dev-site/doc/example/DetailViewDivided.jsx
packages/terra-clinical-detail-view/src/terra-dev-site/doc/example/DetailViewDividedSmallerTitles.jsx
packages/terra-clinical-detail-view/tests/jest/DetailList.test.jsx
packages/terra-clinical-detail-view/tests/jest/DetailView.test.jsx
packages/terra-clinical-detail-view/tests/jest/__snapshots__/DetailList.test.jsx.snap
packages/terra-clinical-detail-view/tests/jest/__snapshots__/DetailView.test.jsx.snap

Currently, the larger texts that are acting as a heading are hard coded as an h1 (title of detail view) or built using div (secondary title and title of detail list). This breaks the proper structure of the page and the screen readers cannot properly relate the information.
- The main title uses the appropriate heading level that the consumer wants and does not default to H1. If the level is not passed in, the default heading level would be set to H2.
- The secondaryTitles are a level below the main title if both the title and the secondaryTitles are passed in and the detailList title is a level below that.
- The screen reader calls out the different titles with appropriate heading levels and there is proper structure to the page.
This change …

[terra-clinical-detail-view] Allow users to select a heading level for title elements

---

packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json
packages/terra-clinical-result/src/ClinicalResultBloodPressure.jsx
packages/terra-clinical-result/src/terra-dev-site/doc/example/clinical-result-blood-pressure/ClinicalResultBloodPressureExtraDisplays.jsx
packages/terra-clinical-result/src/terra-dev-site/test/clinical-result/TestResults.jsx
packages/terra-clinical-result/tests/jest/ClinicalResultBloodPressure.test.jsx
packages/terra-clinical-result/tests/jest/__snapshots__/ClinicalResultBloodPressure.test.jsx.snap
packages/terra-clinical-result/translations/de.json
packages/terra-clinical-result/translations/en-AU.json
packages/terra-clinical-result/translations/en-CA.json
packages/terra-clinical-result/translations/en-GB.json
packages/terra-clinical-result/translations/en-US.json
packages/terra-clinical-result/translations/en.json
packages/terra-clinical-result/translations/es-ES.json
packages/terra-clinical-result/translations/es-US.json
packages/terra-clinical-result/translations/es.json
packages/terra-clinical-result/translations/fi-FI.json
packages/terra-clinical-result/translations/fr-FR.json
packages/terra-clinical-result/translations/fr.json
packages/terra-clinical-result/translations/nl-BE.json
packages/terra-clinical-result/translations/nl.json
packages/terra-clinical-result/translations/pt-BR.json
packages/terra-clinical-result/translations/pt.json
packages/terra-clinical-result/translations/sv-SE.json
packages/terra-clinical-result/translations/sv.json

When we have additional displays (concept, DateTime) as part of blood pressure results, we will need to restructure them so that the screen reader understands them as a group.
* A new prop was added to allow the consumers to make the blood pressure to be grouped. When the prop is set to true, the blood pressure results will be understood as a group. The group name/label is set to "Blood Pressure {dateTime}". 
When there are additional displays along with the blood pressure results, the accessibility tooling can recognize the cell as a group context.
When the prop is false:
https://github.com/cerner/terra-clinical/assets/55503680/6dbf8784-2222-4199-b432-66bc5b68f36f
When the prop is true: …

[terra-clinical-result] Restructure the Blood Pressure with additional displays as a group

---

packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/src/_ClinicalResultDisplay.jsx
packages/terra-clinical-result/tests/jest/ClinicalResult.test.jsx
packages/terra-clinical-result/tests/jest/__snapshots__/ClinicalResult.test.jsx.snap
packages/terra-clinical-result/translations/de.json
packages/terra-clinical-result/translations/en-AU.json
packages/terra-clinical-result/translations/en-CA.json
packages/terra-clinical-result/translations/en-GB.json
packages/terra-clinical-result/translations/es-ES.json
packages/terra-clinical-result/translations/es-US.json
packages/terra-clinical-result/translations/es.json
packages/terra-clinical-result/translations/fi-FI.json
packages/terra-clinical-result/translations/fr-FR.json
packages/terra-clinical-result/translations/fr.json
packages/terra-clinical-result/translations/nl-BE.json
packages/terra-clinical-result/translations/nl.json
packages/terra-clinical-result/translations/pt-BR.json
packages/terra-clinical-result/translations/pt.json
packages/terra-clinical-result/translations/sv-SE.json
packages/terra-clinical-result/translations/sv.json

When trying to validate the alt text for strikethroughs I see that the clinical result site page has an error message. In the dev tools I’m seeing the message “TypeError: Cannot read properties of undefined (reading 'unit')“
I believe my issue is a small check that differs between the clinical result display and the blood pressure display files.
You can see in the clinical result blood pressure display file I’m checking the unit is valid like so: https://github.com/cerner/terra-clinical/pull/870/files#diff-167a4e0b1d0ca2ee4064ed5b2c27e92feee651e13b3b21766c1ad4e538a18a77R48 
But I in the clinical result display file I didn’t use the optional chaining operator (?.): https://github.com/cerner/terra-clinical/pull/870/files#diff-7431c9460fef4d7dc39515e8a588b9374dfdf2c11c98373005aaf3e5e0b8bd3eR9 …

[terra-clinical-result] Add optional chaining operator to clinical result display and update translations

---

packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json
packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.jsx
packages/terra-clinical-result/src/flowsheet-result-cell/FlowsheetResultCell.module.scss
packages/terra-clinical-result/src/result-name-header-cell/ResultNameHeaderCell.jsx
packages/terra-clinical-result/src/result-name-header-cell/ResultNameHeaderCell.module.scss
packages/terra-clinical-result/src/result-time-header-cell/ResultTimeHeaderCell.jsx
packages/terra-clinical-result/src/terra-dev-site/test/clinical-result/flowsheet-result-cell/SemanticTableWithFlowsheetResultCell.test.jsx
packages/terra-clinical-result/src/terra-dev-site/test/clinical-result/result-name-header-cell/SemanticTableWithResultNameHeaderCell.test.jsx
packages/terra-clinical-result/src/terra-dev-site/test/clinical-result/result-time-header-cell/SemanticTableWithResultTimeHeaderCell.test.jsx
packages/terra-clinical-result/tests/jest/flowsheet-result-cell/__snapshots__/FlowsheetResultCell.test.jsx.snap
packages/terra-clinical-result/tests/jest/result-name-header-cell/__snapshots__/ResultNameHeaderCell.test.jsx.snap
packages/terra-clinical-result/tests/jest/result-time-header-cell/__snapshots__/ResultTimeHeaderCell.test.jsx.snap

FlowsheetResultCell, ResultNameHeaderCell, and ResultTimeHeaderCell are presumed to be used as part of a table in which they do not provide the proper context of a Cell or Header Cell for a table. 
We need to change the HTML tags from div to the proper corresponding tags for Header Cells and Cells. That would be _td_ for FlowsheetResultCell and _th_ for ResultNameHeaderCell and ResultTimeHeaderCell.
Also needed to add site tests for each in order to properly validate this change, this is because the 'tables' created on the site currently are not actual semantic html tables. That means the screenreader doesn't pick up on the new context of cell or header cell, just reads them as it has been previously. This is good in that changing the tags doesn't cause any visual …

[terra-clinical-result] Update Result Time/Name header cells and FlowsheetResultCell to use proper HTML tag

---

packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/src/result-time-header-cell/ResultTimeHeaderCell.jsx
packages/terra-clinical-result/src/result-time-header-cell/ResultTimeHeaderCell.module.scss
packages/terra-clinical-result/tests/jest/result-time-header-cell/__snapshots__/ResultTimeHeaderCell.test.jsx.snap

Updated the ResultTimeHeaderCell component to use `<time>` html tags for the date and time.
The ResultTimeHeaderCell component is now using `<time>` html tags for the date and time rather than divs. I also added a visually hidden space between the date and time to resolve an issue with JAWS combining the two and reading them incorrectly.
So the date and time are read to screen reader users in an understandable way.
https://github.com/cerner/terra-clinical/assets/37230460/c6919048-2add-4467-95ba-f1e237f99889
https://github.com/cerner/terra-clinical/assets/37230460/532209a2-267f-4fb8-8fb0-1c837d759fac
Voiceover and JAWS do not officially support the `<time>` html …

[terra-clinical-result] Update ResultTimeHeaderCell to use <time> html tags

---

packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/src/result-time-header-cell/ResultTimeHeaderCell.jsx
packages/terra-clinical-result/tests/jest/result-time-header-cell/__snapshots__/ResultTimeHeaderCell.test.jsx.snap

When merging changes for the most recent release two of our PRs didn't play together properly and it was missed. We are seeing some issues with spacing in the ResultTimeHeaderCell component. When in a semantic table the time and date are squished together instead of being on separate newlines. This only effects the semantic examples. 
Issue with semantic table:
Looks fine in non-semantic example:
Update: This lead us to seeing several different issues with how the time tag is working. After a long discussion we have decided to remove it entirely.
Change the time tags back to divs, also remove the hidden text between the two.
---
Thank you for …

[terra-clinical-result] Remove <time> tags from ResultTimeHeaderCell

---

packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/src/DetailList.jsx
packages/terra-clinical-detail-view/src/terra-dev-site/test/clinical-detail-view/DetailList/LargeItemList.test.jsx
packages/terra-clinical-detail-view/tests/jest/DetailList.test.jsx
packages/terra-clinical-detail-view/tests/jest/__snapshots__/DetailList.test.jsx.snap

Updated Detail List to accept null as children
When creating an unordered list, we access the child's id. If null is passed, then the component throws an error. Now we check if the child exists before returning the `li` element.
When null is passed as a child, the component shouldn't throw an error. 
UXPLATFORM-9223
---
@cerner/terra

[terra-clinical-detail-view] Update Detail List to accept null as children

---

package.json

This PR updates the `lint:js` script in the root level `package.json` so that the maximum number of eslint warnings is zero, so that our lint PR checks will fail when there are warnings.
This change is identical to https://github.com/cerner/terra-core/pull/3832.
Tested by running the lint script locally and as part of the PR check.
UXPLATFORM-9206 
---
@cerner/terra

Update lint:js script

---

packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-detail-view/src/terra-dev-site/doc/clinical-detail-view/ClinicalDetailView.1.doc.mdx
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json
packages/terra-clinical-result/src/terra-dev-site/doc/ClinicalResult/ClinicalResult.1.doc.mdx

Locked uuid dependency to 7.0.3 for consistency across Terra repos.
---
@cerner/terra

[clinical-detail-view][clinical-result] locked uuid to 7.0.3

---

packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/src/DetailView.jsx
packages/terra-clinical-detail-view/tests/jest/DetailView.test.jsx
packages/terra-clinical-detail-view/tests/jest/__snapshots__/DetailView.test.jsx.snap

Terra-Clinical-Detailview was updated to remove empty <div> which was causing additional space on the detail-view component as shown in below screenshot when we not provide any of the title section elements (title, secondaryTitles, subtitles, accessory).
To remove the extra space added due to empty div conditional rendering has been implemented in clinical-detail-view component. extra space shown in above screenshot is removed after code change, same can be seen in below screenshot
Tested with Jest Snapshot to ensure `title-sections div` is not rendered when title elements(title, secondaryTitles, subtitles, accessory) are not specified. …

[Terra-clinical-detailview] Fixes issue of empty space when no elements provided for title section

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json

- terra-clinical-data-grid@2.45.0
- terra-clinical-detail-view@3.35.0
- terra-clinical-item-view@4.10.0
---
@cerner/terra

Releases Following Terra Clinical components

---

.github/actions/setup/action.yml
.npmrc
package.json

This PR upgrades the repo set up to support NPMv9 so to help upgrade the infrastructure and be up to date with our tech stack. 
Since Node 14 ships with NPMv6, the cicd was updated to utilize NPMv9.
This was tested by successfully running `npm install` and building the project with both NPM versions (6 & 9).
---
@cerner/terra

Upgrade to support NPMv9

---

packages/terra-clinical-detail-view/src/terra-dev-site/doc/clinical-detail-view/ClinicalDetailView.1.doc.mdx
packages/terra-clinical-detail-view/tests/jest/DetailList.test.jsx
packages/terra-clinical-detail-view/tests/jest/DetailView.test.jsx
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/src/ClinicalResultBloodPressure.jsx
packages/terra-clinical-result/src/terra-dev-site/doc/ClinicalResult/ClinicalResult.1.doc.mdx
packages/terra-clinical-result/tests/jest/ClinicalResultBloodPressure.test.jsx

Currently the uuid test mocks are hard coded. In order to ensures that every test is fresh and independent of each other, the proposed solution was to use beforeAll() to set up the mock. As jest.mock can't be used inside of the tests or inside beforeAll, jest.spyOn was used instead of jest.mock.
1. Hard-coded jest.mock were replaced with jest.spyOn inside the beforeAll().
2. The mocks were restored in afterAll().
3. The testing section in documentation was updated to reflect the suggested testing method.
**This PR is a part of following JIRA:**
UXPLATFORM-9515

jest.mock replaced with jest.spyOn

---

packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-item-view/src/ItemView.jsx
packages/terra-clinical-item-view/src/terra-dev-site/doc/clinical-item-view/AccessibilityGuide.4.doc.mdx
packages/terra-clinical-item-view/src/terra-dev-site/doc/example/ItemViewTwoColumnWithHeader.jsx
packages/terra-clinical-item-view/src/terra-dev-site/doc/example/ItemViewWithHeader.jsx

Added an accessibility guide for Clinical Item View
So users have a reference for accessibility guidelines and changes we've made to the component.
UXPLATFORM-8569
---
@cerner/terra

[terra-clinical-item-view] Accessibility guide

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json

- terra-clinical-data-grid@2.48.0
- terra-clinical-item-view@4.13.0

Release 10/03/23

---

packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json
packages/terra-clinical-onset-picker/src/OnsetPicker.jsx
packages/terra-clinical-onset-picker/tests/jest/OnsetPicker.test.jsx
packages/terra-clinical-onset-picker/tests/jest/__snapshots__/OnsetPicker.test.jsx.snap

Fixes VO issues.
- Fixes repeated announcement of legend in fields.
- Fixes repeated announcement of options in dynamically rendered fields.
- Legend was announced twice for each field and when dropdown is opened. 
- Fields rendered after granularity selection had repetitive announcements.
**NOTE**
Form select (`select-field`) issues need to be addressed to make onset picker accessible due to repeated announcement of selected item in dropdown.
UXPLATFORM-10100 
---
@cerner/terra

[terra-clinical-onset-picker] Fixes screen reader issues

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/clinicalDataGrid.1.doc.mdx

Added deprecation notice and badge to terra clinical data grid
Terra clinical data grid does not comply with accessibility guidelines and was replaced by flowsheet data grid
UXPLATFORM-9930 
---
@cerner/terra

Terra Clinical Data Grid - Added Deprecation Notice

---

packages/terra-clinical-data-grid/.npmignore
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-detail-view/.npmignore
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-header/.npmignore
packages/terra-clinical-header/package.json
packages/terra-clinical-item-display/.npmignore
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/.npmignore
packages/terra-clinical-item-view/package.json
packages/terra-clinical-label-value-view/.npmignore
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-onset-picker/.npmignore
packages/terra-clinical-onset-picker/package.json
packages/terra-clinical-result/.npmignore
packages/terra-clinical-result/package.json

This PR replaces `.npmignore` files with the `files` prop to denote what files will be published. The `.npmignore` works by blacklisting files, while `files` works by whitelisting files to be published. This change was made as it is more convenient to keep track of files that need to be published than finding potential files that don't need to be published. It also results in fewer issues when running `npm pack` locally.
This was tested by running `npm pack` on `terra-clinical-header` and verifying that all necessary files are included:
---
@cerner/terra

Replace `.npmignores` with `file` field

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json

- terra-clinical-data-grid@2.50.0
- terra-clinical-detail-view@3.37.0
- terra-clinical-header@3.30.0
- terra-clinical-item-display@4.11.0
- terra-clinical-item-view@4.14.0
- terra-clinical-label-value-view@3.32.0
- terra-clinical-onset-picker@4.38.0
- terra-clinical-result@1.23.0
---
@cerner/terra

release-1-3-24

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json

The following components were released:
- terra-clinical-data-grid@2.51.0
- terra-clinical-item-view@4.15.0
- terra-clinical-result@1.24.0
---
@cerner/terra

Release 06/03

---

packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/src/Header.jsx
packages/terra-clinical-header/src/Header.module.scss
packages/terra-clinical-header/tests/jest/Header.test.jsx
packages/terra-clinical-header/tests/jest/__snapshots__/Header.test.jsx.snap

Added flex wrap to start and end content.
MPages require the content of clinical header to wrap instead of scroll.
UXPLATFORM-10197 
---
@cerner/terra

[terra-clinical-header] Wrapped start and end content

---

packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json

- terra-clinical-header@3.31.2
- terra-clinical-onset-picker@4.39.0
---
@cerner/terra

Release 02/04

---

packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/src/OnsetPicker.module.scss
packages/terra-clinical-onset-picker/src/clinical-lowlight-theme/OnsetPicker.module.scss
packages/terra-clinical-onset-picker/src/orion-fusion-theme/OnsetPicker.module.scss

It has been reported, that the value of the **--terra-clinical-onset-picker-year-select-min-width** variable in fusion theme is can be overridden by the same name variable coming from deprecated **orion-fusion-theme** package, which sometimes appears as dependency in some projects. To avoid that, the variable was renamed to --terra-clinical-onset-picker**-calendar**-year-select-min-width.
The new variable being populated instead of the old one:
UXPLATFORM-10364

renamed year select min-width css variable

---

packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/src/Header.jsx
packages/terra-clinical-header/src/Header.module.scss
packages/terra-clinical-header/tests/jest/Header.test.jsx
packages/terra-clinical-header/tests/jest/__snapshots__/Header.test.jsx.snap

Removed title div when value is not provided for text prop.
Title div taking up space even if there is no value leaving less space for children.
UXPLATFORM-10359 
---
@cerner/terra

[terra-clinical-header] Removed title div when value is not provided for text prop.
