cerner/terra-clinical

CONTRIBUTORS.md
packages/terra-clinical-detail-view/LICENSE
packages/terra-clinical-detail-view/NOTICE
packages/terra-clinical-detail-view/README.md
packages/terra-clinical-detail-view/docs/README.md
packages/terra-clinical-detail-view/docs/themeable-variables.md
packages/terra-clinical-detail-view/lib/DetailView.js
packages/terra-clinical-detail-view/lib/DetailView.scss
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-detail-view/src/DetailView.jsx
packages/terra-clinical-detail-view/src/DetailView.scss
packages/terra-clinical-detail-view/tests/jest/DetailView.test.jsx
packages/terra-clinical-detail-view/tests/jest/__snapshots__/DetailView.test.jsx.snap
packages/terra-clinical-detail-view/tests/nightwatch.conf.js
packages/terra-clinical-detail-view/tests/nightwatch/DetailViewDivided.jsx
packages/terra-clinical-detail-view/tests/nightwatch/DetailViewNoDivider.jsx
packages/terra-clinical-detail-view/tests/nightwatch/DetailViewTestRoutes.jsx
packages/terra-clinical-detail-view/tests/nightwatch/DetailViewTests.jsx
packages/terra-clinical-detail-view/tests/nightwatch/detail-view-spec.js
packages/terra-clinical-site/package.json
packages/terra-clinical-site/src/App.jsx
packages/terra-clinical-site/src/Index.jsx
packages/terra-clinical-site/src/TestLinks.jsx
packages/terra-clinical-site/src/examples/detail-view/DetailViewDivided.jsx
packages/terra-clinical-site/src/examples/detail-view/DetailViewNoDivider.jsx
packages/terra-clinical-site/src/examples/detail-view/Index.jsx

Ported from the core repo.
The Detail View component allows you to create a view with text at different levels of importance. A detail view can contain a title, subtitle, graphic visualization, and a list of components that can display information at a more detailed level.

Terra clinical detail view

---

packages/terra-clinical-detail-view/package.json

Commits for the v0.1.0 release

v0.1.0 Release

---

packages/terra-clinical-item-view/lib/ItemView.js
packages/terra-clinical-item-view/src/ItemView.jsx
packages/terra-clinical-item-view/tests/jest/ItemView.test.jsx
packages/terra-clinical-item-view/tests/jest/__snapshots__/ItemView.test.jsx.snap
packages/terra-clinical-site/src/examples/item-view/ItemViewTwoColumn.jsx

Correct the slice logic to return 8 items.

 Bug fix for sliced elements.

---

jestsetup.js
packages/terra-clinical-detail-view/lib/DetailView.js
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-detail-view/src/DetailView.jsx
packages/terra-clinical-error-view/lib/ErrorView.js
packages/terra-clinical-error-view/package.json
packages/terra-clinical-error-view/src/ErrorView.jsx
packages/terra-clinical-header/lib/Header.js
packages/terra-clinical-header/package.json
packages/terra-clinical-header/src/Header.jsx
packages/terra-clinical-item-view/lib/Comment.js
packages/terra-clinical-item-view/lib/Display.js
packages/terra-clinical-item-view/lib/ItemView.js
packages/terra-clinical-item-view/package.json
packages/terra-clinical-item-view/src/Comment.jsx
packages/terra-clinical-item-view/src/Display.jsx
packages/terra-clinical-item-view/src/ItemView.jsx
packages/terra-clinical-label-value-view/lib/LabelValueView.js
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-label-value-view/src/LabelValueView.jsx
packages/terra-clinical-no-data-view/lib/NoDataView.js
packages/terra-clinical-no-data-view/package.json
packages/terra-clinical-no-data-view/src/NoDataView.jsx
packages/terra-clinical-site/src/App.jsx

Added terra-base as a dependency to mimic the [change](https://github.com/cerner/terra-core/pull/251) in terra-core. Additionally, this fixes #20.
@cerner/terra

Add terra-base as dependency.

---

README.md
packages/terra-clinical-label-value-view/package.json

v0.1.0 release of terra-clinical-label-item-view

v0.1.0 release of terra-clinical-label-value-view

---

README.md
lerna.json
packages/terra-clinical-header/package.json

0.1.0 release of terra-clinical-header

v0.1.0 Header Release

---

README.md
lerna.json
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-header/package.json
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/package.json
packages/terra-clinical-label-value-view/package.json

Release of clinical item view/display

Release of clinical item view

---

README.md

Add quick access to the README file for each package. Addresses Issue #61.
@cerner/terra

Update README with links to each package's README file

---

.github/ISSUE_TEMPLATE.md

A new component/enhancement template was added to the git issue template for consistent logging of new components/features. 
@cerner/terra

Updated GIT Issue Template

---

lerna.json

Adding packages to ignore

---

packages/terra-clinical-detail-view/src/DetailView.scss
packages/terra-clinical-error-view/src/ErrorView.scss
packages/terra-clinical-header/src/Header.scss
packages/terra-clinical-item-display/src/ItemComment.scss
packages/terra-clinical-item-display/src/ItemDisplay.scss
packages/terra-clinical-item-view/src/ItemView.scss
packages/terra-clinical-label-value-view/src/LabelValueView.scss
packages/terra-clinical-modal-manager/package.json
packages/terra-clinical-modal-manager/src/ModalManager.jsx
packages/terra-clinical-modal-manager/tests/jest/__snapshots__/ModalManager.test.jsx.snap
packages/terra-clinical-no-data-view/src/NoDataView.scss
packages/terra-clinical-site/package.json
packages/terra-clinical-site/webpack.config.js
packages/terra-clinical-slide-group/src/Slide.scss

Remove SCSS theming capability

---

lerna.json
packages/terra-clinical-site/.npmignore
packages/terra-clinical-site/package.json
packages/terra-clinical-site/src/Index.jsx
packages/terra-clinical-site/src/examples/modal-manager/ModalManagerDemo.jsx
packages/terra-clinical-site/src/examples/slide-group/SlideGroupDemo.jsx
packages/terra-clinical-site/webpack.config.js

Prepare `clinical-site` to be published.
- Move unpublished dependencies to devDependencies.
- add .npmignore
- add publish scripts

Prepare clinical-site to be published

---

packages/terra-clinical-header/docs/README.md

Minor change. Adding clinical to the heading so it matches the other components on the documentation site. 
@cerner/terra

Updating doc heading

---

packages/terra-clinical-app-delegate/README.md
packages/terra-clinical-application/README.md

Minor: fix path for travis-ci badges
@cerner/terra

travis-ci badge path

---

packages/terra-clinical-item-display/src/ItemComment.scss
packages/terra-clinical-item-display/src/ItemDisplay.scss
packages/terra-clinical-item-display/src/_mixins.scss
packages/terra-clinical-item-view/src/ItemView.scss

Reverts cerner/terra-clinical#102

Revert "Update Item Display Styling"

---

.travis.yml

Update Travis-ci.yml to automaticall deploy the terra clinical site on merge to master
related to https://github.com/cerner/terra-core/pull/509
@cerner/terra

Auto deploy the terra clinical site

---

CONTRIBUTORS.md

It's Terra clinical and I helped.
@cerner/terra

Add Moi to Contributors

---

packages/terra-clinical-site/src/TestLinks.jsx
packages/terra-clinical-site/src/examples/item-view/Index.jsx
packages/terra-clinical-site/src/examples/item-view/ItemViewAll.jsx
packages/terra-clinical-site/src/examples/item-view/ItemViewAllTopAligned.jsx
packages/terra-clinical-site/src/examples/item-view/ItemViewComment.jsx
packages/terra-clinical-site/src/examples/item-view/ItemViewStandard.jsx
packages/terra-clinical-site/src/examples/item-view/ItemViewTwoColumn.jsx
packages/terra-clinical-site/src/examples/item-view/ItemViewTwoColumnStart.jsx

Updated the doc site with realistic examples for terra-clinical-item-view. Addresses issue #41.
@cerner/terra

Update ItemView Site Examples To Be Realistic 

---

packages/terra-clinical-application-site/.npmignore

Add npmignore to terra-clinical-application-site
@cerner/terra

Add npmignore to terra-clinical-application-site

---

packages/terra-clinical-action-header/docs/README.md
packages/terra-clinical-application/docs/README.md
packages/terra-clinical-detail-view/docs/README.md
packages/terra-clinical-error-view/docs/README.md
packages/terra-clinical-header/docs/README.md
packages/terra-clinical-item-collection/docs/README.md
packages/terra-clinical-item-display/docs/README.md
packages/terra-clinical-item-view/docs/README.md
packages/terra-clinical-label-value-view/docs/README.md
packages/terra-clinical-no-data-view/docs/README.md

Add component features doc

---

packages/terra-clinical-action-header/CHANGELOG.md
packages/terra-clinical-application-site/CHANGELOG.md
packages/terra-clinical-application/CHANGELOG.md
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-error-view/CHANGELOG.md
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-no-data-view/CHANGELOG.md
packages/terra-clinical-site/CHANGELOG.md

Adding change logs for the initial 1.0
@cerner/terra

adding change logs

---

packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-label-value-view/src/LabelValueView.jsx
packages/terra-clinical-label-value-view/src/LabelValueView.scss
packages/terra-clinical-label-value-view/tests/jest/LabelValueView.test.jsx
packages/terra-clinical-label-value-view/tests/jest/__snapshots__/LabelValueView.test.jsx.snap
packages/terra-clinical-label-value-view/tests/nightwatch/DefaultLabelValueView.jsx
packages/terra-clinical-label-value-view/tests/nightwatch/NodeValueLabelValueView.jsx
packages/terra-clinical-label-value-view/tests/nightwatch/TextValueLabelValueView.jsx
packages/terra-clinical-label-value-view/tests/nightwatch/label-value-view-spec.js

Migrate Label Value View to CSS Modules.

---

packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-detail-view/src/DetailList.jsx
packages/terra-clinical-detail-view/src/DetailList.scss
packages/terra-clinical-detail-view/src/DetailListItem.jsx
packages/terra-clinical-detail-view/src/DetailListItem.scss
packages/terra-clinical-detail-view/src/DetailView.jsx
packages/terra-clinical-detail-view/src/DetailView.scss
packages/terra-clinical-detail-view/tests/jest/DetailList.test.jsx
packages/terra-clinical-detail-view/tests/jest/DetailListItem.test.jsx
packages/terra-clinical-detail-view/tests/jest/DetailView.test.jsx
packages/terra-clinical-detail-view/tests/jest/__snapshots__/DetailList.test.jsx.snap
packages/terra-clinical-detail-view/tests/jest/__snapshots__/DetailListItem.test.jsx.snap
packages/terra-clinical-detail-view/tests/jest/__snapshots__/DetailView.test.jsx.snap
packages/terra-clinical-detail-view/tests/nightwatch/DetailList/NormalItemList.jsx
packages/terra-clinical-detail-view/tests/nightwatch/DetailList/detail-list-spec.js
packages/terra-clinical-detail-view/tests/nightwatch/DetailListItem/DefaultListItem.jsx
packages/terra-clinical-detail-view/tests/nightwatch/DetailListItem/detail-list-item-spec.js
packages/terra-clinical-detail-view/tests/nightwatch/DetailView/DetailViewDivided.jsx
packages/terra-clinical-detail-view/tests/nightwatch/DetailView/DetailViewNoDivider.jsx
packages/terra-clinical-detail-view/tests/nightwatch/DetailView/detail-view-spec.js

Migrate Detail View to CSS Modules

---

packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/src/ItemComment.jsx
packages/terra-clinical-item-display/src/ItemComment.scss
packages/terra-clinical-item-display/src/ItemDisplay.jsx
packages/terra-clinical-item-display/src/ItemDisplay.scss
packages/terra-clinical-item-display/tests/jest/__snapshots__/ItemComment.test.jsx.snap
packages/terra-clinical-item-display/tests/jest/__snapshots__/ItemDisplay.test.jsx.snap
packages/terra-clinical-item-display/tests/nightwatch/comment/DefaultItemComment.jsx
packages/terra-clinical-item-display/tests/nightwatch/comment/TextItemComment.jsx
packages/terra-clinical-item-display/tests/nightwatch/comment/item-comment-spec.js
packages/terra-clinical-item-display/tests/nightwatch/display/DefaultItemDisplay.jsx
packages/terra-clinical-item-display/tests/nightwatch/display/IconItemDisplay.jsx
packages/terra-clinical-item-display/tests/nightwatch/display/item-display-spec.js
packages/terra-clinical-item-view/tests/nightwatch/CommentItemView.jsx
packages/terra-clinical-item-view/tests/nightwatch/item-view-spec.js

Migrate Item Display to CSS Modules

---

packages/terra-clinical-application/CHANGELOG.md
packages/terra-clinical-application/src/Application.jsx
packages/terra-clinical-application/src/Application.scss
packages/terra-clinical-application/tests/jest/Application.test.jsx
packages/terra-clinical-application/tests/jest/__snapshots__/Application.test.jsx.snap
packages/terra-clinical-application/tests/nightwatch/DefaultApplication.jsx
packages/terra-clinical-application/tests/nightwatch/NoAppDelegateApplication.jsx
packages/terra-clinical-application/tests/nightwatch/application-spec.js

Migrate Application to CSS Modules.

---

packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-item-view/src/ItemView.jsx
packages/terra-clinical-item-view/src/ItemView.scss
packages/terra-clinical-item-view/tests/jest/ItemView.test.jsx
packages/terra-clinical-item-view/tests/jest/__snapshots__/ItemView.test.jsx.snap
packages/terra-clinical-item-view/tests/nightwatch/AccessoryItemView.jsx
packages/terra-clinical-item-view/tests/nightwatch/CommentItemView.jsx
packages/terra-clinical-item-view/tests/nightwatch/DefaultItemView.jsx
packages/terra-clinical-item-view/tests/nightwatch/DisplaysItemView.jsx
packages/terra-clinical-item-view/tests/nightwatch/item-view-spec.js

Migrate Item View to CSS Modules.

---

packages/terra-clinical-action-header/CHANGELOG.md
packages/terra-clinical-action-header/package.json
packages/terra-clinical-action-header/src/ActionHeader.jsx
packages/terra-clinical-action-header/src/ActionHeader.scss
packages/terra-clinical-action-header/tests/jest/ActionHeader.test.jsx
packages/terra-clinical-action-header/tests/nightwatch/BackCloseActionHeader.jsx
packages/terra-clinical-action-header/tests/nightwatch/ChildrenActionHeader.jsx
packages/terra-clinical-action-header/tests/nightwatch/DefaultActionHeader.jsx
packages/terra-clinical-action-header/tests/nightwatch/TitleActionHeader.jsx
packages/terra-clinical-action-header/tests/nightwatch/action-header-spec.js

Migrate Action Header to CSS Modules.

---

package.json

Reflects https://github.com/cerner/terra-core/pull/594#pullrequestreview-49029439 changes, which updated stylelint dependencies to help reduce the deprecation warnings in travis CI.
@cerner/terra

Updated style lint dependencies.

---

packages/terra-clinical-item-collection/tests/nightwatch/item-collection/clinical-item-collection-spec.js
packages/terra-clinical-site/CHANGELOG.md
packages/terra-clinical-site/src/App.jsx
packages/terra-clinical-site/src/Index.jsx
packages/terra-clinical-site/src/TestLinks.jsx
packages/terra-clinical-site/src/examples/demo-application/Index.jsx
packages/terra-clinical-site/src/site.scss

Migrate Site to CSS Modules.

---

packages/terra-clinical-site/CHANGELOG.md
packages/terra-clinical-site/src/examples/header/ContentHeader.jsx

Updated the custom margins placed on the button in the header content example to make it appear bidirectional. Closes #157 
@cerner/terra

Update Margins on Header Example Button .

---

package.json
packages/terra-clinical-action-header/CHANGELOG.md
packages/terra-clinical-action-header/src/ActionHeader.jsx
packages/terra-clinical-application/CHANGELOG.md
packages/terra-clinical-application/src/Application.jsx
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/src/DetailList.jsx
packages/terra-clinical-detail-view/src/DetailListItem.jsx
packages/terra-clinical-detail-view/src/DetailView.jsx
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/src/Header.jsx
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/src/ItemCollection.jsx
packages/terra-clinical-item-collection/src/_TableHeaderCell.jsx

Reflects https://github.com/cerner/terra-core/pull/650
@cerner/terra

Update Stylelint Dependencies 

---

packages/terra-clinical-site/CHANGELOG.md
packages/terra-clinical-site/package.json
packages/terra-clinical-site/src/App.jsx
packages/terra-clinical-site/src/index.html
packages/terra-clinical-site/src/site.scss

Update the display of terra-site to use a slide-panel. Sync with https://github.com/cerner/terra-core/pull/720.
@cerner/terra

Update site to use slide panel

---

packages/terra-clinical-action-header/.npmrc
packages/terra-clinical-application-site/.npmrc
packages/terra-clinical-application/.npmrc
packages/terra-clinical-detail-view/.npmrc
packages/terra-clinical-error-view/.npmrc
packages/terra-clinical-header/.npmrc
packages/terra-clinical-item-collection/.npmrc
packages/terra-clinical-item-display/.npmrc
packages/terra-clinical-item-view/.npmrc
packages/terra-clinical-label-value-view/.npmrc
packages/terra-clinical-no-data-view/.npmrc
packages/terra-clinical-site/.npmrc

Add .npmrc file to individual modules to control output of package-lock.json files
References https://github.com/cerner/terra-core/issues/905

Add .npmrc files to individual packages to control package-lock.json creation

---

packages/terra-clinical-application-site/CHANGELOG.md
packages/terra-clinical-application-site/package.json
packages/terra-clinical-application-site/webpack.config.js
packages/terra-clinical-site/CHANGELOG.md
packages/terra-clinical-site/package.json
packages/terra-clinical-site/webpack.config.js

Aligns with https://github.com/cerner/terra-core/issues/921
* Use rules instead of loaders
* Remove JSON loader as its now included in webpack

Update webpack config

---

.travis.yml

Update travis ci config to use the java8 package instead of installing it directly
@cerner/terra

Update travis ci config to match core.

---

.gitattributes

Sync line endings with core.
@cerner/terra

Sync line endings with core

---

packages/terra-clinical-application-site/README.md

Closes #223
- Update Getting Started Section 
- Removed the Documentation Section terra-clinical-application-site as this is a demo-site only

Application-Site Doc Update

---

packages/terra-clinical-action-header/translations/ar.json
packages/terra-clinical-action-header/translations/es-ES.json
packages/terra-clinical-action-header/translations/es-US.json
packages/terra-clinical-action-header/translations/fi-FI.json
packages/terra-clinical-action-header/translations/fr-FR.json
packages/terra-clinical-action-header/translations/pt-BR.json

Missing Translations for 'ar', 'es-US', 'es-ES', 'fi-FI', 'fr-FR', and 'pt-BR'.
Closes #231

[Action Header] Add New Locale Translations

---

CONTRIBUTORS.md
packages/terra-clinical-item-collection/docs/README.md

My first open source contribution - I hope I have done this correctly 😊 
Changed 'Selectable Implementation Guide' link in Terra Clinical Engineering Page. Relates to #248 
Also added my name to the [CONTRIBUTORS.md] file as per contributing guidelines.
@cerner/terra
Closes #248

Link fix clinical item collection

---

packages/terra-clinical-action-header/package.json
packages/terra-clinical-header/package.json

Loosen Dependency Restrictions for terra-clinical-header components

---

package.json
site.config.js

We're adding a github link and locking terra-dev-site to 0.3.0. The next change is expected to be non-passive (upgrading to webpack 4.0).
Please add your name to the [CONTRIBUTORS.md] file. Adding your name to the [CONTRIBUTORS.md] file signifies agreement to all rights and reservations provided by the [License].
@cerner/terra

Test out dev site in clinical.

---

README.md
packages/terra-clinical-application/docs/README.md
packages/terra-clinical-detail-view/docs/README.md
packages/terra-clinical-header/docs/README.md
packages/terra-clinical-item-collection/docs/README.md
packages/terra-clinical-item-display/docs/README.md
packages/terra-clinical-item-view/docs/README.md
packages/terra-clinical-label-value-view/docs/README.md
packages/terra-clinical-onset-picker/docs/README.md
packages/terra-clinical-site/CHANGELOG.md
packages/terra-clinical-site/package.json
packages/terra-clinical-site/src/examples/action-header/Index.jsx
packages/terra-clinical-site/src/examples/application/Index.jsx
packages/terra-clinical-site/src/examples/detail-view/DetailViewDivided.jsx
packages/terra-clinical-site/src/examples/detail-view/DetailViewDividedSmallerTitles.jsx
packages/terra-clinical-site/src/examples/detail-view/DetailViewNoDivider.jsx
packages/terra-clinical-site/src/examples/detail-view/Index.jsx
packages/terra-clinical-site/src/examples/error-view/Index.jsx
packages/terra-clinical-site/src/examples/header/Index.jsx
packages/terra-clinical-site/src/examples/item-collection/Index.jsx
packages/terra-clinical-site/src/examples/item-display/Index.jsx
packages/terra-clinical-site/src/examples/item-view/Index.jsx
packages/terra-clinical-site/src/examples/label-value-view/Index.jsx
packages/terra-clinical-site/src/examples/no-data-view/Index.jsx
packages/terra-clinical-site/src/examples/onset-picker/Index.jsx

Update site pages to use terra-doc-template.

Use to use terra-doc-template & update ReadMes

---

package.json
wdio.conf.js

This PR is preparing the project for a change that is going to happen in terra-toolkit to support parallelization.  This change will help prevent a major version bump in terra-toolkit.

Prepare for toolkit

---

.travis.yml

Try and improve the builds with caching.

Try to improve builds

---

.travis.yml

Update .travis.yml to ensure cache cleanup

Update .travis.yml to ensure cache cleanup

---

.travis.yml

Clean up cache on failures

---

package.json

Resolves #324 and syncs with https://github.com/cerner/terra-core/pull/1433

Update root stylelint check

---

.travis.yml
package.json

Enable new relic monitoring and clean up travis.yml
@cerner/terra

Enable new relic monitoring and clean up travis.yml

---

packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/package.json
packages/terra-clinical-item-collection/src/ItemCollection.jsx
packages/terra-clinical-item-collection/tests/jest/ItemCollection.test.jsx
packages/terra-clinical-item-collection/tests/jest/__snapshots__/ItemCollection.test.jsx.snap

Missed bumping this to new major version in last update. This corrects the version so using the latest release of terra-ui components will all use terra-responsive-element v3.

Bump responsive element version

---

jestconfig.js

Add jest config testURL to jsdom issue

---

README.md

Realized this is out of date on all read me's. Opening a review here and will open PRs in other repos once this is +1'd.

Update i18n Information

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md

Update issue template to include mentions of terra members that have been worked with so far.

Update issue template with mentions.

---

packages/terra-clinical-application/tests/jest/__snapshots__/Application.test.jsx.snap

We added a new prop to terra-base which broke jest snapshots.

Update Application's Jest Snapshots for new Base release

---

packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/tests/wdio/label-value-view-spec.js

Closes #313. Grabbing some low hanging fruit.

[terra-clinical-label-value-view] - Enable color contrast rule 

---

CONTRIBUTORS.md
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/README.md
packages/terra-clinical-item-collection/src/Item.jsx
packages/terra-clinical-item-collection/src/ItemCollection.jsx

* Update prop descriptions in `ItemCollection.jsx` and `Item.jsx`
* Fix small typo in ItemCollection README
Some interactions between `ItemCollection` and `Item` aren't obvious from the existing docs. This is a refresh of the prop descriptions to make these behaviors more explicit.

Update prop descriptions in ItemCollection.jsx and Item.jsx

---

README.md
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/docs/README.md

Addresses site accessibility issues for https://github.com/cerner/terra-ui/issues/46
@cerner/terra

Improve site accessibility

---

NOTICE
packages/terra-clinical-application/NOTICE
packages/terra-clinical-application/README.md
packages/terra-clinical-data-grid/NOTICE
packages/terra-clinical-data-grid/README.md
packages/terra-clinical-detail-view/NOTICE
packages/terra-clinical-detail-view/README.md
packages/terra-clinical-header/NOTICE
packages/terra-clinical-header/README.md
packages/terra-clinical-item-collection/NOTICE
packages/terra-clinical-item-collection/README.md
packages/terra-clinical-item-display/NOTICE
packages/terra-clinical-item-display/README.md
packages/terra-clinical-item-view/NOTICE
packages/terra-clinical-item-view/README.md
packages/terra-clinical-label-value-view/NOTICE
packages/terra-clinical-label-value-view/README.md
packages/terra-clinical-onset-picker/NOTICE
packages/terra-clinical-onset-picker/README.md

Following the Apache Foundation's guidance on copyright notice: https://www.apache.org/legal/src-headers.html#notice
Resolves cerner/terra-framework#65

Update copyright years

---

README.md

Fix Readme Links

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/src/subcomponents/Cell.jsx
packages/terra-clinical-data-grid/src/terra-dev-site/test/clinical-data-grid/PagedContentDataGrid.test.jsx
packages/terra-clinical-detail-view/src/terra-dev-site/test/clinical-detail-view/DetailList/LargeItemList.test.jsx
packages/terra-clinical-detail-view/src/terra-dev-site/test/clinical-detail-view/DetailList/NormalItemList.test.jsx
packages/terra-clinical-detail-view/tests/jest/DetailList.test.jsx
packages/terra-clinical-detail-view/tests/jest/DetailView.test.jsx
packages/terra-clinical-label-value-view/src/terra-dev-site/test/clinical-label-value-view/MultipleValueLabelValueView.test.jsx
packages/terra-clinical-label-value-view/src/terra-dev-site/test/clinical-label-value-view/NodeValueLabelValueView.test.jsx
packages/terra-clinical-onset-picker/src/OnsetPicker.jsx
packages/terra-clinical-onset-picker/tests/jest/OnsetPicker.test.jsx
packages/terra-clinical-onset-picker/tests/jest/__snapshots__/OnsetPicker.test.jsx.snap

Fix up some lint errors introduced with new version of eslint-react-plugin.

Fix lint errors

---

CONTRIBUTORS.md
package.json

Updated terra-dev-site dependency. Resolves #486

Terra site update

---

CONTRIBUTORS.md
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/src/Header.scss

[terra-clinical-header] Increase rule specificity for the collapsible child element.

---

packages/terra-clinical-item-view/README.md

FIxes issue #501 updated typo bug

---

packages/terra-clinical-item-display/README.md

Fixes issue #500 corrected client to clinical

---

CONTRIBUTORS.md
package.json

…10.0.1.
Updated `stylelint-config-terra` to ^3.0.0 and `stylelint` to ^10.0.1
Resolves #496

StyleLintConfig and StyleLint package version updated to ^3.0.0 and ^10.0.1

---

packages/terra-clinical-application/CHANGELOG.md
packages/terra-clinical-application/tests/wdio/application-spec.js
packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/tests/wdio/data-grid-spec.js
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/tests/wdio/DetailList/detail-list-spec.js
packages/terra-clinical-detail-view/tests/wdio/DetailListItem/detail-list-item-spec.js
packages/terra-clinical-detail-view/tests/wdio/DetailView/detail-view-spec.js
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/tests/wdio/header-spec.js
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/tests/wdio/clinical-item-collection-spec.js
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/tests/wdio/item-display-spec.js
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/tests/wdio/item-view-spec.js
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/tests/wdio/label-value-view-spec.js
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/tests/wdio/onset-spec.js

Update to use Terra.describeViewports to enable tests to run in parallel envs if needed.

Update to use Terra.describeViewports

---

.travis.yml
Dockerfile
docker-compose.yml

Consume the new alpine docker images.
Ref: https://github.com/cerner/terra-framework/pull/981

Consume New Docker Images

---

packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/docs/UPGRADEGUIDE.md

[terra-clinical-onset-picker] Added upgrade guide for v3 to v4

---

packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/README.md
packages/terra-clinical-label-value-view/src/terra-dev-site/doc/clinical-label-value-view/ChangeLog.3.doc.mdx
packages/terra-clinical-label-value-view/src/terra-dev-site/doc/clinical-label-value-view/UpgradeGuide.2.doc.mdx
packages/terra-clinical-label-value-view/src/terra-dev-site/doc/clinical-label-value-view/clinicalLabelValueView.1.doc.mdx

[terra-clinical-label-value-view] Update mdx docs

---

packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-detail-view/src/DetailView.jsx
packages/terra-clinical-detail-view/src/DetailView.module.scss
packages/terra-clinical-detail-view/src/clinical-lowlight-theme/DetailView.module.scss
packages/terra-clinical-detail-view/src/orion-fusion-theme/DetailView.module.scss
packages/terra-clinical-detail-view/tests/jest/DetailView.test.jsx
packages/terra-clinical-detail-view/tests/jest/__snapshots__/DetailView.test.jsx.snap
packages/terra-clinical-detail-view/themes/clinical-lowlight-theme/clinical-lowlight-theme.scss
packages/terra-clinical-detail-view/themes/orion-fusion-theme/orion-fusion-theme.scss

Add theme context to terra-clinical-detail-view
@cerner/terra

[terra-clinical-detail-view] Add theme context

---

packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/src/DetailView.module.scss

- Specify divider display to prevent global styles from overriding/hiding it
Closes #671 
- project tests
@cerner/terra

[terra-clinical-detail-view] Specify Divider Display Style

---

.travis.yml
docker-compose.yml
package.json
wdio.conf.js

Similarly to [terra-core#3072](https://github.com/cerner/terra-core/pull/3072) we're running tests directly on travis instead of a docker container and re-organizing the steps to be more time efficient.  
Closes #
Here's our baseline:
This PR:
@cerner/terra

Improve build times

---

.travis.yml
RELEASE.md
package.json
scripts/release/gitTagMonoRepo.js

Automate releases via travis. This is a companion PR to: cerner/terra-framework#1191
@cerner/terra

Release via travis

---

package.json
packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-result/CHANGELOG.md
scripts/changelog-updater/index.js

Update the change log formatting to be semantically correct and to stop failing the markdown linter.
@cerner/terra

Update change log formatting

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-result/CHANGELOG.md
scripts/changelog-updater/index.js

Back by popular demand, another change log update pull request. This time we switch to a list style and I'm not doing this again.
@cerner/terra

Update change log formatting again

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/package.json
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json

Release terra-clinical
@cerner/terra

Release terra-clinical

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json

Updating components for release
@cerner/terra

8-11 Release

---

package.json
packages/terra-clinical-result/CHANGELOG.md

- update browserslist config terra
Closes #685 
Project tests.
@cerner/terra

update browserslist config terra

---

packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json

Release PR
Closes #
@cerner/terra

Release August 25, 2020

---

packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json

Publish on 9-29-2020

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json

Remove terra-props-table reference
Closes #
@cerner/terra

Remove terra-props-table reference

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/src/subcomponents/Cell.jsx
packages/terra-clinical-data-grid/tests/jest/subcomponents/__snapshots__/Cell.test.jsx.snap
packages/terra-clinical-data-grid/tests/jest/subcomponents/__snapshots__/HeaderCell.test.jsx.snap
packages/terra-clinical-data-grid/tests/jest/subcomponents/__snapshots__/RowSelectionCell.test.jsx.snap

This Pr fixes the accessibility issue for selectable empty cells by making the role for cells as undefined.
Closes #703 
@cerner/terra

[terra-clinical-data-grid] Update Cell to have role undefined for non interactable cell

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/src/subcomponents/Cell.jsx
packages/terra-clinical-data-grid/tests/jest/subcomponents/__snapshots__/Cell.test.jsx.snap
packages/terra-clinical-data-grid/tests/jest/subcomponents/__snapshots__/HeaderCell.test.jsx.snap
packages/terra-clinical-data-grid/tests/jest/subcomponents/__snapshots__/RowSelectionCell.test.jsx.snap

Reverts cerner/terra-clinical#706

Revert "[terra-clinical-data-grid] Update Cell to have role undefined for non interactable cell"

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json

Publish on 11-10-2020

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json

12/8/20 Release

---

README.md
packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/clinicalDataGrid.1.doc.mdx
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/src/terra-dev-site/doc/clinical-detail-view/ClinicalDetailView.1.doc.mdx
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/src/terra-dev-site/doc/clinical-header/clinicalHeader.1.doc.mdx
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/src/terra-dev-site/doc/clinical-item-collection/clinicalItemCollection.1.doc.mdx
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/src/terra-dev-site/doc/clinical-item-display/clinicalItemDisplay.1.doc.mdx
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/src/terra-dev-site/doc/clinical-item-view/clinicalItemView.1.doc.mdx
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/src/terra-dev-site/doc/clinical-label-value-view/clinicalLabelValueView.1.doc.mdx
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/README.md
packages/terra-clinical-onset-picker/src/terra-dev-site/doc/clinical-onset-picker/ClinicalOnsetPicker.1.doc.mdx
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/README.md
packages/terra-clinical-result/src/terra-dev-site/doc/ClinicalResult/ClinicalResult.1.doc.mdx
packages/terra-clinical-result/src/terra-dev-site/doc/ClinicalResult/ClinicalResultBloodPressure.2.doc.mdx
packages/terra-clinical-result/src/terra-dev-site/doc/ClinicalResult/FlowsheetResultCell.3.doc.mdx

Fixed broken links in docs
@cerner/terra

[terra-clinical] Fixed broken links in docs

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/package.json
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json

Updating versions for 1/5/21 release

---

package.json

Update eslint and stylelint
Closes #
@cerner/terra

Update eslint and stylelint

---

.travis.yml

Update travis.yml to use test runner with cli options.
Closes #
@cerner/terra

Update travis.yml to use test runner with cli options

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/package.json
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json

Publish on 3-25-2021

---

.github/CODEOWNERS
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/tests/jest/__snapshots__/OnsetPicker.test.jsx.snap

[terra-clinical] Update CODEOWNERS

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json

Just updating a couple of outdated dependencies.
Closes #
@cerner/terra

Update outdated dependencies.

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/package.json
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json

Release
Closes #
@cerner/terra

Release July 21, 2021

---

packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/src/ClinicalResult.jsx

Closes #764 
https://terra-clinic-prop-desc-ptvevvb.herokuapp.com/components/terra-clinical-result/clinical-result/clinical-result
Tech only change, no UX or Functional review needed.

[terra-clinical-result] Fixed incorrect prop descriptions.

---

packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json

Release 8/17/2021

---

packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json

Publish on 9-21-2021

---

package.json

not a huge savings here, but still worth it.
before:
npm run compile:build  17.03s user 2.46s system 123% cpu 15.741 total
after:
npm run compile:build 20.54s user 3.49s system 289% cpu 8.304 total
Closes #
@cerner/terra

Optimize babel compile step

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json

Release on 11-16
Closes #
@cerner/terra

Release on 11-16

---

packages/terra-clinical-onset-picker/CHANGELOG.md

Since the last release we did in this repo failed initially and then was successful after this change got merged, this change ended up in that release.
Closes #
@cerner/terra

Fix changelog

---

package.json
packages/terra-clinical-header/package.json
packages/terra-clinical-header/src/Header.jsx
packages/terra-clinical-header/src/terra-dev-site/doc/clinical-header/AccessibilityGuide.2.doc.mdx
packages/terra-clinical-header/src/terra-dev-site/doc/example/ClinicalHeaderDocCommon.scss
packages/terra-clinical-header/src/terra-dev-site/doc/example/ContentHeader.jsx
packages/terra-clinical-header/src/terra-dev-site/doc/example/HeaderLongText.jsx
packages/terra-clinical-header/src/terra-dev-site/doc/example/Subheader.jsx
packages/terra-clinical-header/src/terra-dev-site/doc/example/TitleHeader.jsx
packages/terra-clinical-header/src/terra-dev-site/doc/layout-helpers/Whitespace.jsx
packages/terra-clinical-header/src/terra-dev-site/doc/layout-helpers/Whitespace.module.scss
packages/terra-clinical-header/src/terra-dev-site/doc/reference/WebAIMSemanticHeadingContentStructure.jsx
packages/terra-clinical-header/src/terra-dev-site/doc/reference/WebAIMSemanticHeadingContentStructure.scss
packages/terra-clinical-header/src/terra-dev-site/test/clinical-header/ClinicalHeaderTestCommon.module.scss
packages/terra-clinical-header/src/terra-dev-site/test/clinical-header/LabelingRegions.test.jsx
packages/terra-clinical-header/src/terra-dev-site/test/clinical-header/LeftAndRightContentHeader.test.jsx
packages/terra-clinical-header/src/terra-dev-site/test/clinical-header/LeftAndRightContentSubheader.test.jsx
packages/terra-clinical-header/src/terra-dev-site/test/clinical-header/LeftContentHeader.test.jsx
packages/terra-clinical-header/src/terra-dev-site/test/clinical-header/LongTitleAndChildrenHeader.test.jsx
packages/terra-clinical-header/src/terra-dev-site/test/clinical-header/LongTitleAndContentHeader.test.jsx
packages/terra-clinical-header/src/terra-dev-site/test/clinical-header/NoLevelHeader.test.jsx
packages/terra-clinical-header/src/terra-dev-site/test/clinical-header/NoTitleRightContentHeader.test.jsx
packages/terra-clinical-header/src/terra-dev-site/test/clinical-header/RightContentHeader.test.jsx
packages/terra-clinical-header/tests/jest/Header.test.jsx
packages/terra-clinical-header/tests/jest/__snapshots__/Header.test.jsx.snap

Merge Clinical Header Docs updates.
Closes #
@cerner/terra

Clinical header axe  doc updates

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json

- terra-clinical-data-grid@2.35.0
Closes #
@cerner/terra

Publish 03-25-2022

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json

- terra-clinical-data-grid@2.35.1
- terra-clinical-onset-picker@4.31.1
Closes #
@cerner/terra

Publish on 04/19/2022

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json

- terra-clinical-data-grid@2.36.0
Closes #
@cerner/terra

Publish on 06/07/2022

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json

- terra-clinical-data-grid@2.37.0
Closes #
@cerner/terra

Prepare for release 07/12/2022

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json

Includes code fix for staircase effects of highlighted columns in IE : #816 
Closes #
@cerner/terra

Release clinical-data-grid

---

.github/workflows/ci-cd.yml

Update to include the NPM token information and github user to commit tags

Update to include the NPM token information and github user to commit tags

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose-wdio.yml
.devcontainer/docker-compose.yml
README.md
package.json

Adds ability to run npm commands locally on a Docker container using VScode devcontainers setup
[MPAGESCORE-88019](https://jira2.cerner.com/browse/MPAGESCORE-88019)
@cerner/terra

Add ability to use Docker Dev Container locally

---

.devcontainer/docker-compose.yml
README.md

Update readme to include Dev Volume Docker instructions
@cerner/terra

Update readme to include Dev Volume Docker instructions

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/Datagrid.1.doc.mdx
packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/Datagrid.json
packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/Datagrid.jsx
packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithColumnHighlight.jsx
packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithColumnResizing.jsx
packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithCustomContent.jsx
packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithNoPinnedColumns.jsx
packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithPaging.7.doc.mdx
packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithPaging.jsx
packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithSelections.jsx
packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithSubsections.jsx
packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithoutFill.jsx

In anticipation of accessibility testing, the terra-clinical-data-grid examples were updated to make it easier to follow the screen reader.
Closes #
Please see the Jira (https://jira2.cerner.com/browse/UXPLATFORM-8491) for screenshots
Instead of hardcoding the data, the data is fetched from a JSON file. Modifying the content of the file will modify the examples.
@cerner/terra

Update clinical-data-grid examples UXPLATFORM-8491

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci-cd.yml
.github/workflows/pr-close.yml
.github/workflows/pr-preview.yml

Pr preview

---

.github/workflows/ci-cd.yml

fixing preview overriding

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/package.json

The following packages will be released
- terra-clinical-data-grid@2.40.0
- terra-clinical-detail-view@3.29.0
- terra-clinical-header@3.26.0
- terra-clinical-label-value-view@3.28.0
Closes #
@cerner/terra

Release 04/21/23

---

packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json
packages/terra-clinical-onset-picker/tests/jest/__snapshots__/OnsetPicker.test.jsx.snap

This PR updates snapshots for `terra-clinical-onset-picker` caused by a dependency update, so that snapshots are up to date and don't cause failures.
---
@cerner/terra

Update Jest snapshots

---

packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/src/ItemDisplay.jsx
packages/terra-clinical-item-display/src/terra-dev-site/doc/clinical-item-display/clinicalItemDisplay.1.doc.mdx
packages/terra-clinical-item-display/src/terra-dev-site/doc/example/DefaultComment.jsx
packages/terra-clinical-item-display/src/terra-dev-site/doc/example/TextStylesDisabled.jsx
packages/terra-clinical-item-display/src/terra-dev-site/test/clinical-item-display/display/DisabledItemDisplay.test.jsx
packages/terra-clinical-item-display/tests/jest/ItemDisplay.test.jsx
packages/terra-clinical-item-display/tests/wdio/item-display-spec.js

Deprecated `isDisabled` prop as this feature does not meet accessibility guidelines. 
UXPLATFORM-8934 
---
@cerner/terra

[terra-clinical-item-display] Deprecating isDisabled prop

---

packages/terra-clinical-item-collection/tests/jest/__snapshots__/Item.test.jsx.snap
packages/terra-clinical-item-collection/tests/jest/__snapshots__/ItemCollection.test.jsx.snap
packages/terra-clinical-item-collection/tests/jest/__snapshots__/_ListView.test.jsx.snap
packages/terra-clinical-item-collection/tests/jest/__snapshots__/_TableView.test.jsx.snap
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-display/src/ItemDisplay.jsx
packages/terra-clinical-item-display/src/terra-dev-site/doc/clinical-item-display/clinicalItemDisplay.1.doc.mdx
packages/terra-clinical-item-display/src/terra-dev-site/doc/example/TextStyleMeaning.jsx
packages/terra-clinical-item-display/src/terra-dev-site/test/clinical-item-display/display/MeaningItemDisplay.test.jsx
packages/terra-clinical-item-display/src/terra-dev-site/test/clinical-item-display/display/TextStyleItemDisplay.test.jsx
packages/terra-clinical-item-display/tests/jest/ItemDisplay.test.jsx
packages/terra-clinical-item-display/tests/jest/__snapshots__/ItemComment.test.jsx.snap
packages/terra-clinical-item-display/tests/jest/__snapshots__/ItemDisplay.test.jsx.snap
packages/terra-clinical-item-display/translations/en-US.json
packages/terra-clinical-item-display/translations/en.json
packages/terra-clinical-item-view/tests/jest/__snapshots__/ItemView.test.jsx.snap
packages/terra-clinical-onset-picker/tests/jest/__snapshots__/OnsetPicker.test.jsx.snap

Added new `meaning` prop to allow consumers to assign a meaning to the ItemDisplay text, for screen readers to use. The strikethrough style will have a default meaning of 'deletion' in English, to simulate the behavior of the semantic `<del>` HTML element.
This change allows users of screen readers to be aware of text having strikethrough styling, to meet a11y requirements. It also allows consumers to define a meaning for any text, regardless of the style.
Tested with JAWS in Edge browser and VoiceOver in Safari, Chrome, and Firefox.
UXPLATFORM-6840 
---
@cerner/terra

[terra-clinical-item-display] Add hidden text meaning to strikethrough style

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/package.json
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json

Release PR for May 15

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/package.json
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json

Reverts cerner/terra-clinical#850

Revert "Release PR for May 15"

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-item-collection/CHANGELOG.md
packages/terra-clinical-item-collection/package.json
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json

- terra-clinical-data-grid@2.41.0
- terra-clinical-item-collection@4.30.1
- terra-clinical-item-display@4.7.0
- terra-clinical-item-view@4.7.0
- terra-clinical-onset-picker@4.33.0
---
@cerner/terra

release May 15

---

packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/src/ItemDisplay.jsx
packages/terra-clinical-item-display/tests/jest/ItemDisplay.test.jsx
packages/terra-clinical-item-display/tests/jest/__snapshots__/ItemDisplay.test.jsx.snap

Added `<strong>` around strong style text elements and `<span>` around non-strong style text elements.
To add semantic elements to the component so that context can be provided to screen reader. 
UXPLATFORM-8590 
---
@cerner/terra

[terra-clinical-item-display] Adding semantics

---

packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/tests/jest/ItemView.test.jsx
packages/terra-clinical-item-view/tests/jest/__snapshots__/ItemView.test.jsx.snap

Updating consumption of terra-clinical-item-display in jest tests since with recent INTL changes it became to high level to just shallow render.
Jest tests were changed to better consume and render `item-display` in snapshots while also updating tests to test specific things to not only rely on Jest snapshots.
`terra-clinical-item-display` was recently update to use `injectintl` function which was causing it to only render high level shallows of itself in Jest. Also tests were dependent on just jest snapshots and no other criteria.
UXPLATFORM-9008 
---
@cerner/terra

[terra-clinical-item-view] Updating jests to properly consume item-display

---

packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-display/src/ItemDisplay.jsx
packages/terra-clinical-item-display/src/terra-dev-site/doc/example/TextStyleMeaning.jsx
packages/terra-clinical-item-display/tests/jest/ItemDisplay.test.jsx
packages/terra-clinical-item-display/tests/jest/__snapshots__/ItemDisplay.test.jsx.snap

VisuallyHiddenText now "wraps" the ItemDisplay text to provide screen reader support for text styling. Removes the previous implementation of using an aria-label on a parent span element. See original change here: https://github.com/cerner/terra-clinical/pull/843
Use of aria-label is not recommended for non-interactive elements, such as divs and spans, or elements without roles. 
Tested with JAWS in Edge browser and with VoiceOver in Safari, Chrome, and Firefox.
UXPLATFORM-9060 
---
@cerner/terra

[terra-clinical-item-display] Update text style meaning to use VisuallyHiddenText

---

packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/src/ItemComment.jsx
packages/terra-clinical-item-display/tests/jest/ItemComment.test.jsx
packages/terra-clinical-item-display/tests/jest/__snapshots__/ItemComment.test.jsx.snap
packages/terra-clinical-item-display/translations/de.json
packages/terra-clinical-item-display/translations/en-GB.json
packages/terra-clinical-item-display/translations/en-US.json
packages/terra-clinical-item-display/translations/en.json
packages/terra-clinical-item-display/translations/es.json
packages/terra-clinical-item-display/translations/fr.json
packages/terra-clinical-item-display/translations/nl.json
packages/terra-clinical-item-display/translations/pt.json
packages/terra-clinical-item-display/translations/sv.json
packages/terra-clinical-item-view/tests/jest/ItemView.test.jsx
packages/terra-clinical-item-view/tests/jest/__snapshots__/ItemView.test.jsx.snap

Added a11yLabel prop to Item comment icon
changes done to support accessibility
UXPLATFORM-8884 
---
@cerner/terra

[terra-clinical-item-display] Added a11yLabel prop to ItemComment Icon

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json

- terra-clinical-data-grid@2.42.0
- terra-clinical-detail-view@3.30.0
- terra-clinical-item-display@4.8.0
- terra-clinical-item-view@4.8.0
- terra-clinical-label-value-view@3.29.0
- terra-clinical-result@1.17.0

Prepare for release June 14

---

CONTRIBUTORS.md
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/src/DetailList.jsx
packages/terra-clinical-detail-view/src/DetailList.module.scss
packages/terra-clinical-detail-view/src/DetailListItem.jsx
packages/terra-clinical-detail-view/src/terra-dev-site/doc/example/DetailViewDivided.jsx
packages/terra-clinical-detail-view/src/terra-dev-site/doc/example/DetailViewDivided.module.scss
packages/terra-clinical-detail-view/src/terra-dev-site/doc/example/DetailViewDividedSmallerTitles.jsx
packages/terra-clinical-detail-view/src/terra-dev-site/doc/example/DetailViewNoDivider.jsx
packages/terra-clinical-detail-view/tests/jest/DetailList.test.jsx
packages/terra-clinical-detail-view/tests/jest/__snapshots__/DetailList.test.jsx.snap

Updated the DetailList component to use HTML list elements rather than divs.
- Added a new `isLabelValuePairList` prop to the DetailList component.
- Updated the DetailList component to be:
- an unordered list when `isLabelValuePairList` is not provided or is set to false
- a description list when `isLabelValuePairList` is set to true
- So screen readers can understand the DetailList component as a description list when it contains label-value pairs and as an unordered list when it contains other HTML elements.
https://github.com/cerner/terra-clinical/assets/37230460/f17dfcf4-1fe1-42e1-9b10-62d8260f7df3
https://github.com/cerner/terra-clinical/assets/37230460/475e454a-3a80-4dad-9a3e-2b170f75cfb3
In addition to …

[terra-clinical-detail-view] Update DetailList to use HTML list elements

---

packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json

- terra-clinical-detail-view@3.31.0
- terra-clinical-result@1.18.0

Release June 22 2023

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/tests/jest/__snapshots__/DataGrid.test.jsx.snap

Updating jest snapshots  due to change in terra-content-container.
---
@cerner/terra

[terra-clinical-data-grid] Updating  jest snapshots

---

packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json

Downgrade UUID in packages from 7.0.3 to 3.4.0
Package version
For better compatibility with other projects.
---
@cerner/terra

Downgrade UUID in packages from 7.0.3 to 3.4.0

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json

- terra-clinical-data-grid@2.44.0
- terra-clinical-detail-view@3.34.0
- terra-clinical-header@3.27.0
- terra-clinical-item-display@4.9.0
- terra-clinical-item-view@4.9.0
- terra-clinical-label-value-view@3.31.0
- terra-clinical-onset-picker@4.34.0
- terra-clinical-result@1.21.0

Release Aug 2 2023

---

.devcontainer/docker-compose-wdio.yml
README.md

Updated the docker compose file for wdio tests to match the 4.0.0 release of terra-functional-testing (https://github.com/cerner/terra-toolkit/blob/main/packages/terra-functional-testing/src/docker/docker-compose.yml).
Using the dev container and running the wdio tests would not pull in the latest chrome version, causing screenshot mismatches.
---
@cerner/terra

Update docker-compose-wdio.yml for dev containers

---

packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json

The following packages were released:
- terra-clinical-header@3.28.0
- terra-clinical-onset-picker@4.35.0
---
@cerner/terra

Release 14/08

---

packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/src/terra-dev-site/doc/clinical-onset-picker/ClinicalOnsetPicker.1.doc.mdx

A blurb is added on the Terra Doc Site about having visible labels for the form fields
This was added to provide more context about the recent changes in having visible labels for the fields. 
UXPLATFORM-9508 
---
@cerner/terra

[terra-clinical-onset-picker] Update Terra Doc Site with blurb about having visible labels for the form fields

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-detail-view/CHANGELOG.md
packages/terra-clinical-detail-view/package.json
packages/terra-clinical-item-display/CHANGELOG.md
packages/terra-clinical-item-display/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json
packages/terra-clinical-label-value-view/CHANGELOG.md
packages/terra-clinical-label-value-view/package.json
packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json
packages/terra-clinical-result/CHANGELOG.md
packages/terra-clinical-result/package.json

- terra-clinical-data-grid@2.46.0
- terra-clinical-detail-view@3.36.0
- terra-clinical-item-display@4.10.0
- terra-clinical-item-view@4.11.0
- terra-clinical-label-value-view@3.31.1
- terra-clinical-onset-picker@4.36.0
- terra-clinical-result@1.22.0

Release September 21, 2023

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json

- terra-clinical-data-grid@2.47.0
- terra-clinical-item-view@4.12.0

Release 09/26/23

---

packages/terra-clinical-data-grid/CHANGELOG.md
packages/terra-clinical-data-grid/package.json
packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json
packages/terra-clinical-item-view/CHANGELOG.md
packages/terra-clinical-item-view/package.json

- terra-clinical-data-grid@2.49.0
- terra-clinical-header@3.29.0
- terra-clinical-item-view@4.13.1

Release 10/11/23

---

packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json

- terra-clinical-onset-picker@4.37.0
---
@cerner/terra

release-4-1-24

---

packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json

- terra-clinical-header@3.31.0
---
@cerner/terra

Release 21/3

---

packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/src/Header.module.scss

Changed flex-direction from column to row for start and end content.
Changed to fix below issue in MPages components.
Before 
After
---
@cerner/terra

[terra-clinical-header] Changed flex direction from column to row

---

packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json

- terra-clinical-header@3.31.1
---
@cerner/terra

Release 26/3

---

packages/terra-clinical-onset-picker/CHANGELOG.md
packages/terra-clinical-onset-picker/package.json

- terra-clinical-onset-picker@4.40.0

Release April 11, 2024

---

packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json

- terra-clinical-header@3.32.0
---
@cerner/terra

Release 15/04

---

packages/terra-clinical-header/CHANGELOG.md
packages/terra-clinical-header/package.json

- terra-clinical-header@3.33.0
---
@cerner/terra

Release 25/04
